[package]
name = "jb-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
env_logger = "0.11.0"
futures-util = "0.3.30"
indicatif = "0.17.7"
log = "0.4.20"
reqwest = { version = "0.11.23", features = ["blocking","json","stream"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tokio = "1.35.1"
