[package]
name = "jb-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jb-lib = { path = "../jb-lib" }
clap = "4.4"
colored = "2.1"
env_logger = "0.11"
log = "0.4"
anyhow = "1.0"
