name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      RUSTFLAGS: -Dwarnings
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2.7.0
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Test
        run: cargo test --workspace
      - name: Check
        run: cargo check --locked --workspace

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      RUSTFLAGS: -Dwarnings
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2.7.0
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Build
        run: cargo build --all --all-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v2.7.0
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Clippy
        run: cargo clippy --workspace --tests -- -Dwarnings -Dclippy::all -Dclippy::pedantic

  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/install@cargo-outdated
      - run: cargo outdated --workspace --exit-code 1