name: CI

on: [push, pull_request]

env:
  BINARY_NAME: jb

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      RUSTFLAGS: -Dwarnings
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2.7.3
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Test
        run: cargo test --workspace
      - name: Check
        run: cargo check --locked --workspace

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      RUSTFLAGS: -Dwarnings
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2.7.3
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Build
        run: cargo build --all --all-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v2.7.3
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Clippy
        run: cargo clippy --workspace --tests -- -Dwarnings -Dclippy::all -Dclippy::pedantic

  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/install@cargo-outdated
      - run: cargo outdated --workspace --exit-code 1

  release:
    name: Release
    needs: [test, build, clippy, outdated]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    timeout-minutes: 45
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for tags and changes

      - name: Install Git Cliff
        env:
          VERSION: 1.4.0
        run: |
          export directory=$(mktemp -d)
          cd "$directory"
          
          wget "https://github.com/orhun/git-cliff/releases/download/v${{ env.VERSION }}/git-cliff-${{ env.VERSION }}-x86_64-unknown-linux-gnu.tar.gz"
          tar -xvf "git-cliff-${{ env.VERSION }}-x86_64-unknown-linux-gnu.tar.gz" --strip-components 1
          sudo mv git-cliff /usr/local/bin/
          
          cd -
          rm -rf "$directory"

      - name: Check if a release is needed
        id: check_release
        run: |
          export LATEST_VERSION=$(git describe --tags --abbrev=0)
          export BUMPED_VERSION=$(git cliff --unreleased --bump --context | jq -r ".[0].version")
          if [ "$LATEST_VERSION" = "$BUMPED_VERSION" ]; then
            echo "needed=false" >> "$GITHUB_OUTPUT"
          else
            echo "previous_version=$LATEST_VERSION" >> "$GITHUB_OUTPUT"
            echo "version=$BUMPED_VERSION" >> "$GITHUB_OUTPUT"
            echo "needed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Build release
        run: |
          mkdir -p dist
          cargo build --release --locked
          strip "target/release/${{ env.BINARY_NAME }}"
          cp "target/release/${{ env.BINARY_NAME }}" "dist/${{ env.BINARY_NAME }}-x86_64"

      - name: Set up Git
        if: steps.check_release.outputs.needed == 'true'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}+${{ github.actor_id }}@users.noreply.github.com"

      - name: Generate changelog, bump version and tag
        if: steps.check_release.outputs.needed == 'true'
        run: |
          git cliff --bump --config .github/cliff.toml > CHANGELOG.md
          sed -i "0,/^version =/s/^version =.*/version = \"${{ steps.check_release.outputs.version }}\"/" ./jb/Cargo.toml
        
          git add CHANGELOG.md jb/Cargo.toml
          git commit -m "chore: bump version to ${{ steps.check_release.outputs.version }}"
          git tag -a "v${{ steps.check_release.outputs.version }}" -m "Release v${{ steps.check_release.outputs.version }}"
          git push --follow-tags

      - name: Generate release body
        if: steps.check_release.outputs.needed == 'true'
        run: |
          git cliff ${{ steps.check_release.outputs.previous_version }}..v${{ steps.check_release.outputs.version }} --config .github/cliff.toml --strip all > RELEASE.md

      - name: Release
        if: steps.check_release.outputs.needed == 'true'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/${{ env.BINARY_NAME }}-*"
          tag: v${{ steps.check_release.outputs.version }}
          name: Release v${{ steps.check_release.outputs.version }}
          bodyFile: RELEASE.md