name: Release

on:
  workflow_call:
    inputs:
      bumped_version:
        type: string
        description: 'The version that was bumped'
        required: true
      latest_tag:
        type: string
        description: 'The latest tag'
        required: true

env:
  BINARY_NAME: jb

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      RUSTFLAGS: -Dwarnings
      CARGO_TERM_COLOR: always
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            distrib: unknown-linux-gnu
            toolchain: stable

          - arch: x86_64
            distrib: unknown-linux-musl
            toolchain: stable

          - arch: aarch64
            distrib: unknown-linux-gnu
            toolchain: stable

          - arch: arm
            distrib: unknown-linux-gnueabihf
            toolchain: stable

    steps:
      - uses: actions/checkout@v4

      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall -y cross --git https://github.com/cross-rs/cross

      - name: Build
        run: cross build --release --target ${{ matrix.arch }}-${{ matrix.distrib }}

      - name: Strip
        # Attempt to strip the binary, but don't fail if it doesn't work (since it's not available on all platforms)
        run: strip target/${{ matrix.arch }}-${{ matrix.distrib }}/release/${{ env.BINARY_NAME }} || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-${{ matrix.arch }}-${{ matrix.distrib }}
          path: target/${{ matrix.arch }}-${{ matrix.distrib }}/release/${{ env.BINARY_NAME }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 45
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall -y git-cliff

      - name: Set up Git
        if: steps.check_release.outputs.needed == 'true'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Generate changelog & Bump version
        if: steps.check_release.outputs.needed == 'true'
        run: |
          git cliff --bump --config .github/cliff.toml > CHANGELOG.md
          sed -i "0,/^version =/s/^version =.*/version = \"${{ inputs.bumped_version }}\"/" jb/Cargo.toml
          
          git add CHANGELOG.md jb/Cargo.toml
          git commit -m "chore(version): bump version to ${{ inputs.bumped_version }}"
          git tag -a "v${{ inputs.bumped_version }}" -m "Release v${{ inputs.bumped_version }}"
          git push --follow-tags

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-x86_64-unknown-linux-gnu
          path: dist/jb_x86_64-unknown-linux-gnu/${{ env.BINARY_NAME }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-x86_64-unknown-linux-musl
          path: dist/jb_x86_64-unknown-linux-musl/${{ env.BINARY_NAME }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-aarch64-unknown-linux-gnu
          path: dist/jb_aarch64-unknown-linux-gnu/${{ env.BINARY_NAME }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-arm-unknown-linux-gnueabihf
          path: dist/jb_arm-unknown-linux-gnueabihf/${{ env.BINARY_NAME }}

      - name: Package
        # Make a tar.gz archive for each binary, named after the target
        run: |
          for f in dist/*; do
            chmod +x $f/${{ env.BINARY_NAME }}
            tar -czf $f.tar.gz -C $f ${{ env.BINARY_NAME }}
            rm -rf $f
          done

      - name: Generate release body
        run: |
          git cliff ${{ inputs.latest_tag }}..v${{ inputs.bumped_version }} --config .github/cliff.toml --strip all > RELEASE.md

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.tar.gz"
          bodyFile: RELEASE.md
          tag: v${{ inputs.bumped_version }}
          name: Release v${{ inputs.bumped_version }}
